tenant/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :assignments
  root to: 'assignments#new'
end

tenant/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

tenant/app/models/assignment.rb
require 'grade'

class Assignment < ApplicationRecord
  acts_as_tenant(:tenant)
  attr_accessor :java_source_zip

  has_attached_file :diagram
  validates_attachment :diagram, content_type: { content_type: ["image/jpg", "image/jpeg", "image/png", "image/gif", "image/svg+xml"] }

  attribute :grades, ::GradeType.new
end

tenant/app/models/grade.rb
class Grade
  include Virtus.model

  attribute :complete, Boolean
  attribute :comments, String

  def description
    ["Complete: #{complete ? 'Yes' : 'No'}", "Comments: #{comments}"].join(",\n")
  end
end

class GradeType < ActiveRecord::Type::Value
  def deserialize(value)
    decoded = ActiveSupport::JSON.decode(value)
    Grade.new(decoded)
  end

  def changed_in_place?(raw_old_value, new_value)
    serialize(new_value) != raw_old_value
  end

  def serialize(value)
    value.to_json
  end
end

tenant/app/models/tenant.rb
class Tenant < ApplicationRecord
end

tenant/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  acts_as_tenant(:tenant)
  validates_uniqueness_to_tenant :email

  has_many :assignments
end

tenant/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  set_current_tenant_through_filter
  before_action :set_tenant

  def set_tenant
    current_tenant = Tenant.find_by_path!(ENV['RAILS_RELATIVE_URL_ROOT'])
    set_current_tenant(current_tenant)
  end
end

tenant/app/controllers/assignments_controller.rb
require 'open3'
require 'zip'

class AssignmentsController < ApplicationController

  before_action :authenticate_user!

  def index
    @assignments = current_user.assignments
  end

  def new
    @assignment = current_user.assignments.build
  end

  def create
    @assignment = current_user.assignments.build(assignment_params)

    tempdir = Dir.mktmpdir
    begin
      Zip::File.open(@assignment.java_source_zip.tempfile) do |zip_file|
        zip_file.each do |f|
          fpath = File.join(tempdir, f.name)
          zip_file.extract(f, fpath) unless File.exist?(fpath)
        end
      end

      output_filename = "output_#{Time.now.to_i}.png"

      commands = ["scripts/umlparser.sh"] 
      commands.push(tempdir, output_filename)

      output, status = Open3.capture2(*commands)

      if status.exitstatus != 0
        # TODO Error handling
        raise 'hell'
      end

      @assignment.diagram = File.open(output_filename)
      @assignment.save!
      redirect_to edit_assignment_url(@assignment)
    ensure
      FileUtils.remove_entry tempdir
      FileUtils.remove_entry output_filename if File.exist?(output_filename)
    end
  end

  def update
    @assignment = current_user.assignments.find(params[:id])
    @assignment.grades = Grade.new(grade_params)
    if @assignment.save
      redirect_to @assignment
    else
      render :edit
    end
  end

  def show
    @assignment = current_user.assignments.find(params[:id])
  end

  def edit
    @assignment = current_user.assignments.find(params[:id])
  end

  def grade_params
    params.require(:assignment).require(:grades).permit(:points, :comments)
  end

  def assignment_params
    params.require(:assignment).permit(:student_id, :description, :assignment_type, :java_source_zip)
  end
end

tenant/app/helpers/application_helper.rb
module ApplicationHelper
end

tenant/app/views/assignments/edit.html.erb
<div class="col-lg-8">
  <div class="page-header">
    <h3>Output</h3>
  </div>
  <%= image_tag @assignment.diagram.url, style: 'max-width: 700px;' %>
</div>
<div class="col-lg-4">
  <div class="page-header">
    <h3>Grade</h3>
  </div>

  <%= form_for @assignment do |f| %>
    <%= f.simple_fields_for :grades do |grades_form| %>
      <%= grades_form.input :points, label: 'Points', required: true, input_html: {value: @assignment.grades[:points]}  %>
      <%= grades_form.input :comments, label: 'Comments', as: :text, required: false, input_html: {value: @assignment.grades[:comments]} %>
      <%= grades_form.button :submit, 'Update' %>
    <% end %>
  <% end %>
</div>

tenant/app/views/assignments/index.html.erb
<div class="page-header">
  <h3>Assigments</h3>
</div>
<table class="table">
  <tr>
    <th>Student Id</th>
    <th>Assignment Code</td>
    <th>Type</th>
    <th>Actions</th>
    <th>Grade</th>
  </tr>
  <% @assignments.each do |assignment| %>
    <tr>
      <td><%= assignment.student_id %></td>
      <td><%= assignment.description %></td>
      <td><%= assignment.assignment_type.titleize %></td>
      <td><%= link_to('View', assignment) %></td>
      <td><%= assignment.grades.description %></td>
    </tr>
  <% end %>
</table>

tenant/app/views/assignments/new.html.erb
<h3>UML Parser</h3>
<hr>
<%= simple_form_for(@assignment, html: {multipart: true} ) do |f| %>
  <%= f.input :student_id, label: 'Student ID', placeholder: 'Student ID', required: true %>
  <%= f.input :description, label: 'Assignment Code', placeholder: 'Assignment Code', required: true %>

  <%= f.label :assignment_type %>
  <%= f.collection_radio_buttons(:assignment_type, [['class', 'Class Diagram']], :first, :last, item_wrapper_tag: :div, item_wrapper_class: :radio, checked: 'class') { |b| content_tag(:label) { b.radio_button + b.label } }  %>
  <%= f.input :java_source_zip, as: :file, :label => 'Java Source Files zip' %>
  <%= f.button :submit, 'Submit' %>
<% end %>

tenant/app/views/assignments/show.html.erb
<div class="col-lg-8">
  <div class="page-header">
    <h3>Output</h3>
  </div>
  <%= image_tag @assignment.diagram.url, style: 'max-width: 700px;' %>
</div>
<div class="col-lg-4">
  <div class="page-header">
    <%= link_to('Edit Grade', edit_assignment_path(@assignment), class: 'pull-right') %>
    <h3>Grade</h3>
  </div>
  <div class="col-lg-12">
    <dl class="dl-horizontal">
    <% @assignment.grades.attributes.each do |k, v| %>
      <dt><%= k.to_s.titleize %></dt>
      <dd><%= v %></dd>
    <% end %>
    </dl>
  </div>
</div>

tenant/app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-dismissible alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

tenant/app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Home', root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
      </ul>
    </div>
  </div>
</nav>

tenant/app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>

tenant/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "SaasTenant" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top" style="background-color: <%= current_tenant.settings['theme'] rescue 'blue' %>">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to current_tenant.name, root_path, class: 'navbar-brand' %>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
          <% if user_signed_in? %>
            <li><%= link_to "New Assignment", root_path %></li>
            <li><%= link_to "Assignments", assignments_path %></li>
            <li>
            <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>        
            </li>
          <% else %>
            <li>
            <%= link_to('Login', new_user_session_path)  %>  
            </li>
          <% end %>
          </ul>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-12">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
    </div> <!-- /container -->

  </body>
</html>